version: "3.8"

services:
  web:
    container_name: web
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    container_name: datab
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=slb
      - POSTGRES_PASSWORD=jade
      - POSTGRES_DB=nutella_dev
      
volumes:
  postgres_data: